# Site settings
title: Paulo Villa's Blog
email: prcvilla@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Website for my recent posting on random stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://prcvilla.github.io" # the base hostname & protocol for your site
github_username:  prcvilla

# Build settings
markdown: kramdown
